# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(802, 481)
        mainwindow.setMinimumSize(QtCore.QSize(802, 481))
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gbReg = QtWidgets.QGroupBox(self.centralwidget)
        self.gbReg.setObjectName("gbReg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbReg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbMIDIFile = QtWidgets.QLabel(self.gbReg)
        self.lbMIDIFile.setObjectName("lbMIDIFile")
        self.gridLayout_2.addWidget(self.lbMIDIFile, 4, 0, 1, 1)
        self.btnFolderOpen = QtWidgets.QPushButton(self.gbReg)
        self.btnFolderOpen.setObjectName("btnFolderOpen")
        self.gridLayout_2.addWidget(self.btnFolderOpen, 1, 4, 1, 1)
        self.lbFolderPath = QtWidgets.QLabel(self.gbReg)
        self.lbFolderPath.setObjectName("lbFolderPath")
        self.gridLayout_2.addWidget(self.lbFolderPath, 1, 0, 1, 1)
        self.tbBankFileName = QtWidgets.QLineEdit(self.gbReg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbBankFileName.sizePolicy().hasHeightForWidth())
        self.tbBankFileName.setSizePolicy(sizePolicy)
        self.tbBankFileName.setAutoFillBackground(False)
        self.tbBankFileName.setReadOnly(True)
        self.tbBankFileName.setObjectName("tbBankFileName")
        self.gridLayout_2.addWidget(self.tbBankFileName, 3, 2, 1, 1)
        self.tbMIDIFileName = QtWidgets.QLineEdit(self.gbReg)
        self.tbMIDIFileName.setReadOnly(True)
        self.tbMIDIFileName.setObjectName("tbMIDIFileName")
        self.gridLayout_2.addWidget(self.tbMIDIFileName, 4, 2, 1, 1)
        self.lbBankFile = QtWidgets.QLabel(self.gbReg)
        self.lbBankFile.setObjectName("lbBankFile")
        self.gridLayout_2.addWidget(self.lbBankFile, 3, 0, 1, 1)
        self.btnMIDIUpload = QtWidgets.QPushButton(self.gbReg)
        self.btnMIDIUpload.setObjectName("btnMIDIUpload")
        self.gridLayout_2.addWidget(self.btnMIDIUpload, 4, 4, 1, 1)
        self.btnBankUpload = QtWidgets.QPushButton(self.gbReg)
        self.btnBankUpload.setObjectName("btnBankUpload")
        self.gridLayout_2.addWidget(self.btnBankUpload, 3, 4, 1, 1)
        self.lbName = QtWidgets.QLabel(self.gbReg)
        self.lbName.setObjectName("lbName")
        self.gridLayout_2.addWidget(self.lbName, 0, 0, 1, 1)
        self.tbNameOnElectone = QtWidgets.QLineEdit(self.gbReg)
        self.tbNameOnElectone.setReadOnly(True)
        self.tbNameOnElectone.setObjectName("tbNameOnElectone")
        self.gridLayout_2.addWidget(self.tbNameOnElectone, 0, 2, 1, 1)
        self.tbFolderName = QtWidgets.QLineEdit(self.gbReg)
        self.tbFolderName.setReadOnly(True)
        self.tbFolderName.setObjectName("tbFolderName")
        self.gridLayout_2.addWidget(self.tbFolderName, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.gbReg, 0, 1, 1, 1)
        self.lvFolder = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvFolder.sizePolicy().hasHeightForWidth())
        self.lvFolder.setSizePolicy(sizePolicy)
        self.lvFolder.setObjectName("lvFolder")
        self.gridLayout.addWidget(self.lvFolder, 0, 0, 2, 1)
        self.gbMIDI = QtWidgets.QGroupBox(self.centralwidget)
        self.gbMIDI.setObjectName("gbMIDI")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbMIDI)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbLead = QtWidgets.QCheckBox(self.gbMIDI)
        self.cbLead.setObjectName("cbLead")
        self.gridLayout_3.addWidget(self.cbLead, 6, 2, 1, 1)
        self.cbLower = QtWidgets.QCheckBox(self.gbMIDI)
        self.cbLower.setObjectName("cbLower")
        self.gridLayout_3.addWidget(self.cbLower, 6, 1, 1, 1)
        self.cbUpper = QtWidgets.QCheckBox(self.gbMIDI)
        self.cbUpper.setObjectName("cbUpper")
        self.gridLayout_3.addWidget(self.cbUpper, 6, 0, 1, 1)
        self.btnExLead = QtWidgets.QPushButton(self.gbMIDI)
        self.btnExLead.setObjectName("btnExLead")
        self.gridLayout_3.addWidget(self.btnExLead, 0, 0, 1, 1)
        self.cbFoot = QtWidgets.QCheckBox(self.gbMIDI)
        self.cbFoot.setObjectName("cbFoot")
        self.gridLayout_3.addWidget(self.cbFoot, 7, 0, 1, 1)
        self.btnAllOn = QtWidgets.QPushButton(self.gbMIDI)
        self.btnAllOn.setObjectName("btnAllOn")
        self.gridLayout_3.addWidget(self.btnAllOn, 0, 1, 1, 1)
        self.btnAllOff = QtWidgets.QPushButton(self.gbMIDI)
        self.btnAllOff.setObjectName("btnAllOff")
        self.gridLayout_3.addWidget(self.btnAllOff, 0, 2, 1, 1)
        self.cbKBP = QtWidgets.QCheckBox(self.gbMIDI)
        self.cbKBP.setObjectName("cbKBP")
        self.gridLayout_3.addWidget(self.cbKBP, 7, 1, 1, 1)
        self.cbControl = QtWidgets.QCheckBox(self.gbMIDI)
        self.cbControl.setObjectName("cbControl")
        self.gridLayout_3.addWidget(self.cbControl, 7, 2, 1, 1)
        self.cbXG = QtWidgets.QCheckBox(self.gbMIDI)
        self.cbXG.setObjectName("cbXG")
        self.gridLayout_3.addWidget(self.cbXG, 8, 0, 1, 1)
        self.gridLayout.addWidget(self.gbMIDI, 1, 1, 1, 1)
        mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 22))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        mainwindow.setMenuBar(self.menubar)
        self.actClose = QtWidgets.QAction(mainwindow)
        self.actClose.setObjectName("actClose")
        self.actSave = QtWidgets.QAction(mainwindow)
        self.actSave.setObjectName("actSave")
        self.actOpen = QtWidgets.QAction(mainwindow)
        self.actOpen.setObjectName("actOpen")
        self.menu_F.addAction(self.actOpen)
        self.menu_F.addAction(self.actSave)
        self.menu_F.addAction(self.actClose)
        self.menubar.addAction(self.menu_F.menuAction())

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)
        mainwindow.setTabOrder(self.tbNameOnElectone, self.tbFolderName)
        mainwindow.setTabOrder(self.tbFolderName, self.btnFolderOpen)
        mainwindow.setTabOrder(self.btnFolderOpen, self.tbBankFileName)
        mainwindow.setTabOrder(self.tbBankFileName, self.btnBankUpload)
        mainwindow.setTabOrder(self.btnBankUpload, self.tbMIDIFileName)
        mainwindow.setTabOrder(self.tbMIDIFileName, self.lvFolder)
        mainwindow.setTabOrder(self.lvFolder, self.btnMIDIUpload)
        mainwindow.setTabOrder(self.btnMIDIUpload, self.btnExLead)
        mainwindow.setTabOrder(self.btnExLead, self.btnAllOn)
        mainwindow.setTabOrder(self.btnAllOn, self.btnAllOff)
        mainwindow.setTabOrder(self.btnAllOff, self.cbUpper)
        mainwindow.setTabOrder(self.cbUpper, self.cbLower)
        mainwindow.setTabOrder(self.cbLower, self.cbLead)
        mainwindow.setTabOrder(self.cbLead, self.cbFoot)
        mainwindow.setTabOrder(self.cbFoot, self.cbKBP)
        mainwindow.setTabOrder(self.cbKBP, self.cbControl)
        mainwindow.setTabOrder(self.cbControl, self.cbXG)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "elsnam editor"))
        self.gbReg.setTitle(_translate("mainwindow", "割り当て"))
        self.lbMIDIFile.setText(_translate("mainwindow", "MIDIファイル"))
        self.btnFolderOpen.setText(_translate("mainwindow", "開く"))
        self.lbFolderPath.setText(_translate("mainwindow", "フォルダの場所"))
        self.lbBankFile.setText(_translate("mainwindow", "バルクファイルの名前"))
        self.btnMIDIUpload.setText(_translate("mainwindow", "アップロード"))
        self.btnBankUpload.setText(_translate("mainwindow", "アップロード"))
        self.lbName.setText(_translate("mainwindow", "エレクトーン上の名前"))
        self.gbMIDI.setTitle(_translate("mainwindow", "パート"))
        self.cbLead.setText(_translate("mainwindow", "リードボイス(通常はOFF)"))
        self.cbLower.setText(_translate("mainwindow", "下鍵盤"))
        self.cbUpper.setText(_translate("mainwindow", "上鍵盤"))
        self.btnExLead.setText(_translate("mainwindow", "リードボイス以外ON"))
        self.cbFoot.setText(_translate("mainwindow", "足鍵盤"))
        self.btnAllOn.setText(_translate("mainwindow", "全てON(通常は使わない)"))
        self.btnAllOff.setText(_translate("mainwindow", "全てOFF"))
        self.cbKBP.setText(_translate("mainwindow", "キーボードパーカッション"))
        self.cbControl.setText(_translate("mainwindow", "コントロール"))
        self.cbXG.setText(_translate("mainwindow", "XG"))
        self.menu_F.setTitle(_translate("mainwindow", "ファイル(&F)"))
        self.actClose.setText(_translate("mainwindow", "閉じる"))
        self.actSave.setText(_translate("mainwindow", "保存"))
        self.actOpen.setText(_translate("mainwindow", "ELS_SONG.NAMを開く"))


